# This is a basic workflow to help you get started with Actions

name: 'Build and Release'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [assigned, opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: GitTools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.x'

      - name: Determine GitVersion
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0.9.10
        with:
          useConfigFile: true

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-api-key: ${{ secrets.NUGET_TOKEN }}
          nuget-version: latest

      - name: Update Pack Version
        run: sed -e 's/#.#.#/'${{ steps.gitversion.outputs.fullSemVer }}'/g' -i NetEvolve.EditorConfig.props

      - name: Run NuGet Pack
        run: nuget pack NetEvolve.EditorConfig.nuspec -Version ${{ steps.gitversion.outputs.fullSemVer }} -NoDefaultExcludes
